//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComicManager.ComicDatabase {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComicDatabase.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name bytearray from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileUpload", ReplyAction="*")]
        WebComicManager.ComicDatabase.FileUploadResponse FileUpload(WebComicManager.ComicDatabase.FileUploadRequest request);
        
        // CODEGEN: Generating message contract since element name comic from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePost", ReplyAction="*")]
        WebComicManager.ComicDatabase.DeletePostResponse DeletePost(WebComicManager.ComicDatabase.DeletePostRequest request);
        
        // CODEGEN: Generating message contract since element name PostAllAquireResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostAllAquire", ReplyAction="*")]
        WebComicManager.ComicDatabase.PostAllAquireResponse PostAllAquire(WebComicManager.ComicDatabase.PostAllAquireRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetComicImage", ReplyAction="*")]
        WebComicManager.ComicDatabase.GetComicImageResponse GetComicImage(WebComicManager.ComicDatabase.GetComicImageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileUploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileUpload", Namespace="http://tempuri.org/", Order=0)]
        public WebComicManager.ComicDatabase.FileUploadRequestBody Body;
        
        public FileUploadRequest() {
        }
        
        public FileUploadRequest(WebComicManager.ComicDatabase.FileUploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FileUploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] bytearray;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Blog.ComicDatabase.Comic postName;
        
        public FileUploadRequestBody() {
        }
        
        public FileUploadRequestBody(byte[] bytearray, Blog.ComicDatabase.Comic postName) {
            this.bytearray = bytearray;
            this.postName = postName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileUploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileUploadResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebComicManager.ComicDatabase.FileUploadResponseBody Body;
        
        public FileUploadResponse() {
        }
        
        public FileUploadResponse(WebComicManager.ComicDatabase.FileUploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FileUploadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FileUploadResult;
        
        public FileUploadResponseBody() {
        }
        
        public FileUploadResponseBody(string FileUploadResult) {
            this.FileUploadResult = FileUploadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePost", Namespace="http://tempuri.org/", Order=0)]
        public WebComicManager.ComicDatabase.DeletePostRequestBody Body;
        
        public DeletePostRequest() {
        }
        
        public DeletePostRequest(WebComicManager.ComicDatabase.DeletePostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletePostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Blog.ComicDatabase.Comic comic;
        
        public DeletePostRequestBody() {
        }
        
        public DeletePostRequestBody(Blog.ComicDatabase.Comic comic) {
            this.comic = comic;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePostResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebComicManager.ComicDatabase.DeletePostResponseBody Body;
        
        public DeletePostResponse() {
        }
        
        public DeletePostResponse(WebComicManager.ComicDatabase.DeletePostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletePostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeletePostResult;
        
        public DeletePostResponseBody() {
        }
        
        public DeletePostResponseBody(string DeletePostResult) {
            this.DeletePostResult = DeletePostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostAllAquireRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostAllAquire", Namespace="http://tempuri.org/", Order=0)]
        public WebComicManager.ComicDatabase.PostAllAquireRequestBody Body;
        
        public PostAllAquireRequest() {
        }
        
        public PostAllAquireRequest(WebComicManager.ComicDatabase.PostAllAquireRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostAllAquireRequestBody {
        
        public PostAllAquireRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostAllAquireResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostAllAquireResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebComicManager.ComicDatabase.PostAllAquireResponseBody Body;
        
        public PostAllAquireResponse() {
        }
        
        public PostAllAquireResponse(WebComicManager.ComicDatabase.PostAllAquireResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostAllAquireResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Blog.ComicDatabase.Comic[] PostAllAquireResult;
        
        public PostAllAquireResponseBody() {
        }
        
        public PostAllAquireResponseBody(Blog.ComicDatabase.Comic[] PostAllAquireResult) {
            this.PostAllAquireResult = PostAllAquireResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComicImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComicImage", Namespace="http://tempuri.org/", Order=0)]
        public WebComicManager.ComicDatabase.GetComicImageRequestBody Body;
        
        public GetComicImageRequest() {
        }
        
        public GetComicImageRequest(WebComicManager.ComicDatabase.GetComicImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetComicImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetComicImageRequestBody() {
        }
        
        public GetComicImageRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComicImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComicImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebComicManager.ComicDatabase.GetComicImageResponseBody Body;
        
        public GetComicImageResponse() {
        }
        
        public GetComicImageResponse(WebComicManager.ComicDatabase.GetComicImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetComicImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetComicImageResult;
        
        public GetComicImageResponseBody() {
        }
        
        public GetComicImageResponseBody(string GetComicImageResult) {
            this.GetComicImageResult = GetComicImageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WebComicManager.ComicDatabase.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WebComicManager.ComicDatabase.ServiceSoap>, WebComicManager.ComicDatabase.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebComicManager.ComicDatabase.FileUploadResponse WebComicManager.ComicDatabase.ServiceSoap.FileUpload(WebComicManager.ComicDatabase.FileUploadRequest request) {
            return base.Channel.FileUpload(request);
        }
        
        public string FileUpload(byte[] bytearray, Blog.ComicDatabase.Comic postName) {
            WebComicManager.ComicDatabase.FileUploadRequest inValue = new WebComicManager.ComicDatabase.FileUploadRequest();
            inValue.Body = new WebComicManager.ComicDatabase.FileUploadRequestBody();
            inValue.Body.bytearray = bytearray;
            inValue.Body.postName = postName;
            WebComicManager.ComicDatabase.FileUploadResponse retVal = ((WebComicManager.ComicDatabase.ServiceSoap)(this)).FileUpload(inValue);
            return retVal.Body.FileUploadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebComicManager.ComicDatabase.DeletePostResponse WebComicManager.ComicDatabase.ServiceSoap.DeletePost(WebComicManager.ComicDatabase.DeletePostRequest request) {
            return base.Channel.DeletePost(request);
        }
        
        public string DeletePost(Blog.ComicDatabase.Comic comic) {
            WebComicManager.ComicDatabase.DeletePostRequest inValue = new WebComicManager.ComicDatabase.DeletePostRequest();
            inValue.Body = new WebComicManager.ComicDatabase.DeletePostRequestBody();
            inValue.Body.comic = comic;
            WebComicManager.ComicDatabase.DeletePostResponse retVal = ((WebComicManager.ComicDatabase.ServiceSoap)(this)).DeletePost(inValue);
            return retVal.Body.DeletePostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebComicManager.ComicDatabase.PostAllAquireResponse WebComicManager.ComicDatabase.ServiceSoap.PostAllAquire(WebComicManager.ComicDatabase.PostAllAquireRequest request) {
            return base.Channel.PostAllAquire(request);
        }
        
        public Blog.ComicDatabase.Comic[] PostAllAquire() {
            WebComicManager.ComicDatabase.PostAllAquireRequest inValue = new WebComicManager.ComicDatabase.PostAllAquireRequest();
            inValue.Body = new WebComicManager.ComicDatabase.PostAllAquireRequestBody();
            WebComicManager.ComicDatabase.PostAllAquireResponse retVal = ((WebComicManager.ComicDatabase.ServiceSoap)(this)).PostAllAquire(inValue);
            return retVal.Body.PostAllAquireResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebComicManager.ComicDatabase.GetComicImageResponse WebComicManager.ComicDatabase.ServiceSoap.GetComicImage(WebComicManager.ComicDatabase.GetComicImageRequest request) {
            return base.Channel.GetComicImage(request);
        }
        
        public string GetComicImage(string name) {
            WebComicManager.ComicDatabase.GetComicImageRequest inValue = new WebComicManager.ComicDatabase.GetComicImageRequest();
            inValue.Body = new WebComicManager.ComicDatabase.GetComicImageRequestBody();
            inValue.Body.name = name;
            WebComicManager.ComicDatabase.GetComicImageResponse retVal = ((WebComicManager.ComicDatabase.ServiceSoap)(this)).GetComicImage(inValue);
            return retVal.Body.GetComicImageResult;
        }
    }
}
