//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.ComicDatabase {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comic", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Comic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlogPostField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BlogPost {
            get {
                return this.BlogPostField;
            }
            set {
                if ((object.ReferenceEquals(this.BlogPostField, value) != true)) {
                    this.BlogPostField = value;
                    this.RaisePropertyChanged("BlogPost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ImageName {
            get {
                return this.ImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageNameField, value) != true)) {
                    this.ImageNameField = value;
                    this.RaisePropertyChanged("ImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComicDatabase.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name bytearray from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileUpload", ReplyAction="*")]
        Blog.ComicDatabase.FileUploadResponse FileUpload(Blog.ComicDatabase.FileUploadRequest request);
        
        // CODEGEN: Generating message contract since element name comic from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePost", ReplyAction="*")]
        Blog.ComicDatabase.DeletePostResponse DeletePost(Blog.ComicDatabase.DeletePostRequest request);
        
        // CODEGEN: Generating message contract since element name PostAllAquireResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostAllAquire", ReplyAction="*")]
        Blog.ComicDatabase.PostAllAquireResponse PostAllAquire(Blog.ComicDatabase.PostAllAquireRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetComicImage", ReplyAction="*")]
        Blog.ComicDatabase.GetComicImageResponse GetComicImage(Blog.ComicDatabase.GetComicImageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileUploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileUpload", Namespace="http://tempuri.org/", Order=0)]
        public Blog.ComicDatabase.FileUploadRequestBody Body;
        
        public FileUploadRequest() {
        }
        
        public FileUploadRequest(Blog.ComicDatabase.FileUploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FileUploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] bytearray;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Blog.ComicDatabase.Comic postName;
        
        public FileUploadRequestBody() {
        }
        
        public FileUploadRequestBody(byte[] bytearray, Blog.ComicDatabase.Comic postName) {
            this.bytearray = bytearray;
            this.postName = postName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileUploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileUploadResponse", Namespace="http://tempuri.org/", Order=0)]
        public Blog.ComicDatabase.FileUploadResponseBody Body;
        
        public FileUploadResponse() {
        }
        
        public FileUploadResponse(Blog.ComicDatabase.FileUploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FileUploadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FileUploadResult;
        
        public FileUploadResponseBody() {
        }
        
        public FileUploadResponseBody(string FileUploadResult) {
            this.FileUploadResult = FileUploadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePost", Namespace="http://tempuri.org/", Order=0)]
        public Blog.ComicDatabase.DeletePostRequestBody Body;
        
        public DeletePostRequest() {
        }
        
        public DeletePostRequest(Blog.ComicDatabase.DeletePostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletePostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Blog.ComicDatabase.Comic comic;
        
        public DeletePostRequestBody() {
        }
        
        public DeletePostRequestBody(Blog.ComicDatabase.Comic comic) {
            this.comic = comic;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePostResponse", Namespace="http://tempuri.org/", Order=0)]
        public Blog.ComicDatabase.DeletePostResponseBody Body;
        
        public DeletePostResponse() {
        }
        
        public DeletePostResponse(Blog.ComicDatabase.DeletePostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletePostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeletePostResult;
        
        public DeletePostResponseBody() {
        }
        
        public DeletePostResponseBody(string DeletePostResult) {
            this.DeletePostResult = DeletePostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostAllAquireRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostAllAquire", Namespace="http://tempuri.org/", Order=0)]
        public Blog.ComicDatabase.PostAllAquireRequestBody Body;
        
        public PostAllAquireRequest() {
        }
        
        public PostAllAquireRequest(Blog.ComicDatabase.PostAllAquireRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostAllAquireRequestBody {
        
        public PostAllAquireRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostAllAquireResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostAllAquireResponse", Namespace="http://tempuri.org/", Order=0)]
        public Blog.ComicDatabase.PostAllAquireResponseBody Body;
        
        public PostAllAquireResponse() {
        }
        
        public PostAllAquireResponse(Blog.ComicDatabase.PostAllAquireResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostAllAquireResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Blog.ComicDatabase.Comic[] PostAllAquireResult;
        
        public PostAllAquireResponseBody() {
        }
        
        public PostAllAquireResponseBody(Blog.ComicDatabase.Comic[] PostAllAquireResult) {
            this.PostAllAquireResult = PostAllAquireResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComicImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComicImage", Namespace="http://tempuri.org/", Order=0)]
        public Blog.ComicDatabase.GetComicImageRequestBody Body;
        
        public GetComicImageRequest() {
        }
        
        public GetComicImageRequest(Blog.ComicDatabase.GetComicImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetComicImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetComicImageRequestBody() {
        }
        
        public GetComicImageRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComicImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComicImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Blog.ComicDatabase.GetComicImageResponseBody Body;
        
        public GetComicImageResponse() {
        }
        
        public GetComicImageResponse(Blog.ComicDatabase.GetComicImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetComicImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetComicImageResult;
        
        public GetComicImageResponseBody() {
        }
        
        public GetComicImageResponseBody(string GetComicImageResult) {
            this.GetComicImageResult = GetComicImageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Blog.ComicDatabase.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Blog.ComicDatabase.ServiceSoap>, Blog.ComicDatabase.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blog.ComicDatabase.FileUploadResponse Blog.ComicDatabase.ServiceSoap.FileUpload(Blog.ComicDatabase.FileUploadRequest request) {
            return base.Channel.FileUpload(request);
        }
        
        public string FileUpload(byte[] bytearray, Blog.ComicDatabase.Comic postName) {
            Blog.ComicDatabase.FileUploadRequest inValue = new Blog.ComicDatabase.FileUploadRequest();
            inValue.Body = new Blog.ComicDatabase.FileUploadRequestBody();
            inValue.Body.bytearray = bytearray;
            inValue.Body.postName = postName;
            Blog.ComicDatabase.FileUploadResponse retVal = ((Blog.ComicDatabase.ServiceSoap)(this)).FileUpload(inValue);
            return retVal.Body.FileUploadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blog.ComicDatabase.DeletePostResponse Blog.ComicDatabase.ServiceSoap.DeletePost(Blog.ComicDatabase.DeletePostRequest request) {
            return base.Channel.DeletePost(request);
        }
        
        public string DeletePost(Blog.ComicDatabase.Comic comic) {
            Blog.ComicDatabase.DeletePostRequest inValue = new Blog.ComicDatabase.DeletePostRequest();
            inValue.Body = new Blog.ComicDatabase.DeletePostRequestBody();
            inValue.Body.comic = comic;
            Blog.ComicDatabase.DeletePostResponse retVal = ((Blog.ComicDatabase.ServiceSoap)(this)).DeletePost(inValue);
            return retVal.Body.DeletePostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blog.ComicDatabase.PostAllAquireResponse Blog.ComicDatabase.ServiceSoap.PostAllAquire(Blog.ComicDatabase.PostAllAquireRequest request) {
            return base.Channel.PostAllAquire(request);
        }
        
        public Blog.ComicDatabase.Comic[] PostAllAquire() {
            Blog.ComicDatabase.PostAllAquireRequest inValue = new Blog.ComicDatabase.PostAllAquireRequest();
            inValue.Body = new Blog.ComicDatabase.PostAllAquireRequestBody();
            Blog.ComicDatabase.PostAllAquireResponse retVal = ((Blog.ComicDatabase.ServiceSoap)(this)).PostAllAquire(inValue);
            return retVal.Body.PostAllAquireResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blog.ComicDatabase.GetComicImageResponse Blog.ComicDatabase.ServiceSoap.GetComicImage(Blog.ComicDatabase.GetComicImageRequest request) {
            return base.Channel.GetComicImage(request);
        }
        
        public string GetComicImage(string name) {
            Blog.ComicDatabase.GetComicImageRequest inValue = new Blog.ComicDatabase.GetComicImageRequest();
            inValue.Body = new Blog.ComicDatabase.GetComicImageRequestBody();
            inValue.Body.name = name;
            Blog.ComicDatabase.GetComicImageResponse retVal = ((Blog.ComicDatabase.ServiceSoap)(this)).GetComicImage(inValue);
            return retVal.Body.GetComicImageResult;
        }
    }
}
